site_name: Tari Docs
nav:
# - Introduction: tari-introduction.md
# - Getting Started: tari-templates.md
- Home: index.md
- Hello Ootle!:
  - Getting Started: helloootle/01-getting-started.md
  - Pre-requisites:
    - Setting up the Ootle Wallet: helloootle/02-setting-up-ootle-wallet.md
    - Setting up your IDE: helloootle/03-setting-up-ide-environment.md
    - Create a Web App Project: helloootle/04-creating-a-basic-web-app.md
  - Coding your Project:
    - Adding the Wallet to your App: helloootle/05-adding-your-wallet.md
    - Connect to your Ootle Wallet via your App: helloootle/06-connecting-your-wallet-via-walletconnect.md
    - Introduction to Templates: helloootle/07-accessing-the-counter-template.md
    - Adding the Counter to your Project: helloootle/08-adding-the-counter-to-your-project.md
    - Interacting with Created Counters: helloootle/09-interacting-with-created-counters.md

# - Hackathon: hackathon.md
- Templates: tari-templates.md
- Tari JS Library: tarijs_library_intro.md
- Resource Manager: template-lib-resource-manager.md
        hidden: true

extra_css:
  - stylesheets/extra.css  # Make sure this path is correct relative to your project

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/node-icon.svg
  favicon: assets/images/android-icon-192x192.png
  features:
# Original
#    - navigation.sections
#    - navigation.footer
#    - navigation.indexes
#    - content.tooltips
#    - navigation.tabs
# #   - toc.integrate
#    - toc.follow

# features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
      - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: monokai  