site_name: Tari Docs
nav:
# - Introduction: tari-introduction.md
# - Getting Started: tari-templates.md
- Home: index.md
- Hello Ootle!:
  - Getting Started: helloootle/getting-started.md
  - Pre-requisites:
    - Setting up the Ootle Wallet: setting-up-ootle-wallet.md
    - Setting up your IDE: setting-up-ide-environment.md
- Hackathon: hackathon.md
- Templates: hackathon_templates.md
- Tari JS Library: tarijs_library_intro.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/node-icon.svg
  favicon: assets/images/android-icon-192x192.png
  features:
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - content.tooltips
    - navigation.tabs
 #   - toc.integrate
    - toc.follow
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
      - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true